name: account build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run:
          - mvn -B package --file pom.xml
          - docker version
#      - name: docker build & push aliyun
#        env:
#          aliyun_username: ${{ secrets.Aliyun_Username }}
#          aliyun_password: ${{ secrets.Aliyun_Password }}
#          run:
#            - sudo docker login --username=${aliyun_username} registry.cn-beijing.aliyuncs.com --password=${{ secrets.aliyun_password }}
#            - sudo docker build -t ${{ matrix.image-name }}:${{ matrix.image-version }} .
#            - sudo docker tag ${{ matrix.image-name }}:${{ matrix.image-version }} registry.cn-beijing.aliyuncs.com/mytest1_1/account:${{ matrix.image-version }}
#            - sudo docker push registry.cn-beijing.aliyuncs.com/命名空间/镜像仓库:${{ matrix.image-version }}